openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description

servers:
  - url: "http://localhost:4000/api/v1"
    description: for local host
    

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token


paths:
  /lco:
    get:
      tags:
        - String
      summary: returns a greet message from lco
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: mystring 
  /lcoobject:
    get:
      tags:
        - Object
      summary: returns a objects
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
  /lcoarray:
    get:
      tags:
        - Array
      summary: returns a arrays
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    price:
                      type: number




      